-- Generated from /Users/user/Downloads/Табак.xlsx on 2026-05-26.
-- Fixture imports current tobacco inventory: brands, categories, and tobacco names.
-- Active menu rows come from sheets: Тяжкий, Середній, Легкий, Без тютюна.
-- Sheets "Є але не для меню" and "Запас" are imported as in_stock=true, is_active=false.
-- Strength defaults by sheet: Тяжкий=10, Середній=6, Легкий=3, Без тютюна=1; smoke=4.
BEGIN;

INSERT INTO flavor_categories (slug, name, emoji, sort_order) VALUES
  ('berries', 'Ягоди', '🍓', 20),
  ('fruits', 'Фрукти', '🍏', 30),
  ('dessert', 'Десерт', '🍰', 40),
  ('alcohol', 'Алкоголь', '🍸', 50),
  ('other', 'Інше', '✨', 90)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    emoji = EXCLUDED.emoji,
    sort_order = EXCLUDED.sort_order;

INSERT INTO tobacco_brands (slug, name) VALUES
  ('420', '420'),
  ('arawak', 'ARAWAK'),
  ('art-x', 'ART X'),
  ('buta', 'BUTA'),
  ('chefs', 'CHEF''S'),
  ('creepy', 'CREEPY'),
  ('cult', 'CULT'),
  ('custom', 'CUSTOM'),
  ('dead-horse', 'DEAD HORSE'),
  ('enigma', 'ENIGMA'),
  ('haven', 'HAVEN'),
  ('jibiar', 'JIBIAR'),
  ('just', 'JUST'),
  ('lagom', 'LAGOM'),
  ('loud', 'LOUD'),
  ('molfar', 'MOLFAR'),
  ('musthave', 'MUSTHAVE'),
  ('nakhla', 'NAKHLA'),
  ('orwell', 'ORWELL'),
  ('phantom', 'PHANTOM'),
  ('smoke-mafia', 'SMOKE MAFIA'),
  ('space-tea', 'SPACE TEA'),
  ('spam', 'SPAM'),
  ('swipe', 'SWIPE'),
  ('turbo-figgy-wan', 'TURBO FIGGY WAN'),
  ('unity', 'UNITY'),
  ('white-side', 'WHITE SIDE'),
  ('zodiac', 'ZODIAC')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name;

WITH tobacco_seed (brand_slug, category_slug, name, description, strength, smoke, color, in_stock, is_active, popularity) AS (
  VALUES
    ('420', 'berries', 'Barberry candy', 'Барбарис льодяник · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('420', 'fruits', 'Captain Baldezh', 'Груша лимонад · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('420', 'other', 'Coldbrew', 'Холодний кавовий напій · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('420', 'other', 'Halloween', 'Гарбуз · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('420', 'fruits', 'Kiwi smoothie', 'Ківі коктейль · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('420', 'dessert', 'Peach gelatto', 'Персик морозиво · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('420', 'fruits', 'Pomelo', 'Помело · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('420', 'other', 'Toxic candy', 'Зелене яблуко льодяник лимон · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('arawak', 'dessert', 'Cinnamon pie', 'Кориця пиріг · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('arawak', 'fruits', 'Lemon', 'Лимон · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('arawak', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('arawak', 'other', 'Sour fanta', 'Апельсин фанта · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('arawak', 'other', 'Watermelon gum', 'Енергетик кавун кактус лайм · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('art-x', 'other', 'Apricot', 'Абрикос · Excel category: OTHER · Source: Є але не для меню', 6, 4, '#8a8f98', true, false, 0),
    ('art-x', 'other', 'White grape', 'Виноград · Excel category: OTHER · Source: Є але не для меню', 6, 4, '#8a8f98', true, false, 0),
    ('buta', 'fruits', 'Banana', 'Банан · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('buta', 'fruits', 'Coconut island', 'Кокос · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('buta', 'other', 'Gum', 'Жуйка · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('buta', 'dessert', 'Honey', 'Мед · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('buta', 'fruits', 'Ice green apple', 'Зелене яблуко лід · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('buta', 'berries', 'Ice raspberry', 'Малина лід · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('buta', 'fruits', 'Pina colada', 'Ананас кокос · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('buta', 'fruits', 'POMEGRANATE', 'Гранат · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('buta', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('buta', 'berries', 'Strawberry', 'Полуниця · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('buta', 'dessert', 'Vanilla', 'Ваніль · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('chefs', 'alcohol', 'Cream likor', 'Лікер вершки · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('chefs', 'berries', 'Lil grape', 'Кислий виноград · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('chefs', 'other', 'Pepsi mango', 'Кола манго · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('chefs', 'fruits', 'Pineapple', 'Ананас · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('chefs', 'berries', 'Sour blueberries', 'Кисла чорниця · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('chefs', 'other', 'Sour blueberries Кисла чорниця', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('chefs', 'berries', 'Sour cherry', 'Кисла вишня · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('chefs', 'fruits', 'Sour lemon', 'Кислий лимон · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('chefs', 'fruits', 'Sour pineapple', 'Кислий ананас · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('chefs', 'fruits', 'Sweet watermelon', 'Солодкий кавун · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('creepy', 'other', 'Creeepy cola', 'Кола · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('creepy', 'fruits', 'Creepy Banana', 'Банан · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('creepy', 'dessert', 'Exotic Brekfast', 'Ананас маракуя пластівці · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('creepy', 'dessert', 'Krampus', 'Какао маршмеллоу · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('creepy', 'dessert', 'Papaya sorbet', 'Морозиво папая · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('creepy', 'dessert', 'Strawberry dessert', 'Пиріг полуниця · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('cult', 'dessert', 'Coconut almond', 'Кокос мигдаль · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('cult', 'dessert', 'Oreo', 'Печиво · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('cult', 'dessert', 'Raffaello', 'Кокос цукерки · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('cult', 'other', 'Spiced chai', 'Прянощі чай · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('cult', 'dessert', 'Strawberry cheesecake', 'Полуниця чізкейк · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('custom', 'dessert', 'Айс кенді', 'Цукерки лід м’ята · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('custom', 'berries', 'Йошта агрус', 'Йошта агрус · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('custom', 'berries', 'Кислюча малина', 'Малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('custom', 'fruits', 'Логан фрукт', 'Лонган · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('custom', 'fruits', 'Помело лимон', 'Помело лимон · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('custom', 'other', 'Рожевий бабл гам', 'Жуйка · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('custom', 'berries', 'Червона смородина', 'Червона смородина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('custom', 'berries', 'Шовковиця смузі', 'Шовковиця смузі · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('dead-horse', 'alcohol', 'Aperol spritz', 'Апероль · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('dead-horse', 'fruits', 'Citrus cream', 'Крем сода лимон помело · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('dead-horse', 'berries', 'Grape juice', 'Сік чорний виноград · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('dead-horse', 'alcohol', 'Happy wineday', 'Червоне вино · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('dead-horse', 'other', 'Lemon tea', 'Лимон чай · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('dead-horse', 'dessert', 'Ponchik boy', 'Пончик ягоди · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('dead-horse', 'fruits', 'Sour apple', 'Кисле яблуко · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('dead-horse', 'fruits', 'Tropic ray', 'Манго полуниця кокос · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('dead-horse', 'other', 'Крем сода лимон помело', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('enigma', 'berries', 'Anablanka', 'Ківі полуниця · Excel category: BERRIES;FRUITS · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('enigma', 'other', 'Arctic', 'М’ята · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('enigma', 'fruits', 'Clementines', 'Апельсин · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('enigma', 'other', 'Elixir', 'Хвоя · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('enigma', 'berries', 'Fragaria', 'Суниця · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('enigma', 'fruits', 'Granadilla', 'Маракуя · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('enigma', 'other', 'Kashmir', 'Спеції · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('enigma', 'fruits', 'Nectarinium', 'Нектарин · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('enigma', 'fruits', 'Pyrastep', 'Груша · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'berries', 'Black currant', 'Чорна смородина · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'berries', 'Black grape', 'Чорний виноград · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'berries', 'Blend berry', 'Мікс ягід · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'dessert', 'Bounty', 'Баунті · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('haven', 'dessert', 'Chef cake', 'Полуничний кекс · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('haven', 'other', 'Colder', 'Холод · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('haven', 'berries', 'Dark cherry', 'Темна вишня · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'berries', 'Double mix', 'Подвійне яблуко персик — полуниця · Excel category: BERRIES;FRUITS · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'other', 'Energy', 'Енергетик · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('haven', 'other', 'Flame', 'Цитрус ягоди · Excel category: BERRIES:FRUITS · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('haven', 'fruits', 'Granate', 'Гранатовий фреш · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Grapefruit', 'Грейпфрут · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'other', 'Jelly cola', 'Желейна кола · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('haven', 'fruits', 'Kiwi Ківі', 'Ківі · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Lemon', 'Лимон · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Mango', 'Манго · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Melon', 'Стигла диня · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'One pear', 'Зимова груша · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Pine shock', 'Кислий ананас · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'fruits', 'Red cot', 'Нектарин — абрикос · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'fruits', 'Sour citrus', 'Кислий цитрус · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'berries', 'Strawberries', 'Полуниця суниця · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'fruits', 'Tropical', 'Тропічний мікс · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'berries', 'Twin berry', 'Малина чорниця · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('haven', 'fruits', 'Watermelon', 'Кавун · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('haven', 'other', 'Кислий цитрус', 'Excel category: OTHER · Source: Запас', 10, 4, '#8a8f98', true, false, 0),
    ('jibiar', 'other', 'Ice cactus Кактус лід', 'Excel category: OTHER · Source: Запас', 3, 4, '#8a8f98', true, false, 0),
    ('just', 'other', 'Ice cactus', 'Кактус лід · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('just', 'other', 'Irish cream', 'Вершки ваніль кава · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('just', 'other', 'Pan raas', 'Спеції · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('just', 'dessert', 'Plombir', 'Морозиво шоколад · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('just', 'fruits', 'Poseidon', 'Апельсин грейпфрут маракуя лід · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('just', 'dessert', 'Tiramisu', 'Тірамісу · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('just', 'fruits', 'Two apple', 'Яблуко · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('just', 'dessert', 'Тірамісу', 'Тірамісу · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('lagom', 'other', 'Bergamia', 'Бергамот · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('lagom', 'fruits', 'Crazy frog', 'Кислий манго · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('lagom', 'other', 'Fireflower', 'Квіти перець · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('lagom', 'other', 'Fjord', 'Трави квіти · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('lagom', 'alcohol', 'Glogg', 'Глінтвейн · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('lagom', 'other', 'Lavandeful', 'Лаванда · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('lagom', 'other', 'Moonlight', 'Жасмин зелений чай · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('lagom', 'fruits', 'Punked shock', 'Кислий ананас · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('lagom', 'other', 'Sunset', 'Квіти · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('loud', 'berries', 'Barberry candy', 'Барбарис льодяник · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('loud', 'other', 'Cherry cola', 'Ваніль вишня кола · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('loud', 'fruits', 'Citrus mix', 'Апельсин грейпфрут лайм лимон · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('loud', 'dessert', 'Coconut cookie', 'Кокос печиво · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('loud', 'other', 'Corn’pop', 'Кукурудза попкорн · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('loud', 'other', 'Cream soda', 'Крем лимонад цитрус · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('loud', 'dessert', 'Cremebrulee', 'Лічі малина вершки · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('loud', 'fruits', 'Feijoa lemonade', 'Лимонад фейхоа · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('loud', 'berries', 'Grape vines', 'Виноград · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('loud', 'fruits', 'Lemon drops', 'Лимон льодяник · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('loud', 'berries', 'Raspberry mojo', 'Малина мохіто · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('loud', 'fruits', 'Tangerine', 'Ваніль мандарин · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('loud', 'berries', 'Tea — mix', 'Малина чорниця ягоди · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('loud', 'other', 'Thai spirit', 'Зелений чай імбир манго · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('loud', 'berries', 'Wild strawberry', 'Суниця · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('molfar', 'other', 'For him', 'Апельсин абрикос ваніль бергамот · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('molfar', 'other', 'Вареник з вишнями', 'Вишня · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('molfar', 'other', 'Вендетта', 'Апельсин вишня журавлина лід · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('molfar', 'other', 'Дари Мексики', 'Кактус лайм · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('molfar', 'other', 'Лотос', 'Лотос грейпфрут помело · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('molfar', 'dessert', 'Печиво мармелад', 'Мармелад печиво · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('molfar', 'other', 'Самурай', 'Годжі сенча(зелений чай) · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('molfar', 'fruits', 'Симиренка', 'Зелене яблуко · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('molfar', 'other', 'Смерека', 'Ялинка · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('molfar', 'fruits', 'Фруктовий сад', 'Манго персик · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('molfar', 'other', 'Чорнобаївка', 'Шоколад чорнослив тютюн · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('molfar', 'other', 'Яскрава меліса', 'М’ята · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('musthave', 'other', 'Orange team', 'Апельсин мандарин · Excel category: OTHER · Source: Є але не для меню', 6, 4, '#8a8f98', true, false, 0),
    ('nakhla', 'other', 'Two apple Яблуко', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('orwell', 'berries', 'Banana berry', 'Суниця банан · Excel category: BERRIES;FRUITS · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('orwell', 'dessert', 'Berry dessert', 'Ягідний десерт · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('orwell', 'other', 'Black rose', 'Кола роза · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('orwell', 'berries', 'Blue mist', 'Чорниця з льодом · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('orwell', 'fruits', 'Capri Sun', 'Фруктовий мікс · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'fruits', 'Citrus splash', 'Цитрус з льодом · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('orwell', 'other', 'Cola vanilla', 'Ваніль кола · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('orwell', 'dessert', 'Dark candy', 'Темний льодяник · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('orwell', 'fruits', 'Drive energy', 'Цитрусовий енергетик · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('orwell', 'alcohol', 'Fragolino', 'Полуничне фраголіно · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('orwell', 'fruits', 'Fyger kiwi', 'Ківі фейхоа · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'fruits', 'G.fruit', 'Грейпфрут · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'berries', 'Hubba bubba', 'Чорнична жуйка · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('orwell', 'fruits', 'Lemon X', 'Лимон · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'fruits', 'Lime juice', 'Сік лайму · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'other', 'Mint', 'М''ята · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('orwell', 'berries', 'Mixberry', 'Мікс ягід · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('orwell', 'fruits', 'Mystery tropic', 'Манго маракуя · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'dessert', 'Nut gelato', 'Морозиво горіх · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('orwell', 'fruits', 'Pine star', 'Ананас · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('orwell', 'fruits', 'Red light', 'Кавун — диня · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'fruits', 'Summer peach tea', 'Персик чай лід · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('orwell', 'other', 'Vanilla cola', 'Ванільна кола · Excel category: OTHER · Source: Тяжкий', 10, 4, '#8a8f98', true, true, 0),
    ('orwell', 'fruits', 'Wednesday', 'Ананас манго пітайя чорна смородина · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('orwell', 'berries', 'Вишня — гранат', 'Вишня гранат · Excel category: BERRIES;FRUITS · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('orwell', 'berries', 'Сливовий джем', 'Джем слива · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('phantom', 'fruits', 'Love 66', 'Диня кавун лід · Excel category: FRUITS · Source: Тяжкий', 10, 4, '#f0a523', true, true, 0),
    ('phantom', 'berries', 'Агрус', 'Агрус · Excel category: BERRIES · Source: Тяжкий', 10, 4, '#c5183a', true, true, 0),
    ('phantom', 'dessert', 'Гарячий шоколад', 'Шоколад · Excel category: DESSERTS · Source: Тяжкий', 10, 4, '#c98b3c', true, true, 0),
    ('smoke-mafia', 'other', 'Cactus', 'Кактус · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('smoke-mafia', 'other', 'Gin', 'Коктейль хвоя · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('smoke-mafia', 'fruits', 'Pineapple', 'Ананас · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('smoke-mafia', 'berries', 'Pink bomb', 'Грейпфрут полуниця малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('smoke-mafia', 'alcohol', 'Rum honey', 'Ром мед · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('space-tea', 'dessert', 'Apple candy', 'Зелене червоне яблуко льодяник · Excel category: DESSERTS · Source: Без тютюна', 1, 4, '#c98b3c', true, true, 0),
    ('space-tea', 'fruits', 'Baby strawberry', 'Пиріг суниця · Excel category: FRUITS · Source: Без тютюна', 1, 4, '#f0a523', true, true, 0),
    ('space-tea', 'berries', 'Blueberry', 'Чорниця · Excel category: BERRIES · Source: Без тютюна', 1, 4, '#c5183a', true, true, 0),
    ('space-tea', 'fruits', 'Pomelo lycjee', 'Лічі помело · Excel category: FRUITS · Source: Без тютюна', 1, 4, '#f0a523', true, true, 0),
    ('space-tea', 'berries', 'Raspberry stories', 'Джем малина · Excel category: BERRIES · Source: Без тютюна', 1, 4, '#c5183a', true, true, 0),
    ('space-tea', 'fruits', 'Sicilian orange', 'Сицилійський апельсин · Excel category: FRUITS · Source: Без тютюна', 1, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Абрикос', 'Абрикос · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Ананас лимон', 'Ананас лимон · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Банан', 'Банан · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'other', 'Бергамот ківі', 'Бергамот ківі · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('spam', 'berries', 'Виноград ягоди', 'Виноград ягоди · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'other', 'Вишневий екліпс', 'Вишня жуйка · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('spam', 'berries', 'Вишня папая', 'Вишня папая · Excel category: BERRIES;FRUITS · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'fruits', 'Грейпфрут', 'Грейпфрут · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Екзотичні фрукти', 'Манго маракуя папая лід · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'dessert', 'Желейні ведмедики', 'Мармелад · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('spam', 'fruits', 'Зелений мікс', 'Ківі лайм фейхоа м''ята · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Кавун диня', 'Кавун диня · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Кавуновий лимонад', 'Кавун лимонад · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'fruits', 'Кокос ананас диня', 'Кокос ананас диня · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'other', 'Кокос диня ананас', 'Excel category: OTHER · Source: Запас', 3, 4, '#8a8f98', true, false, 0),
    ('spam', 'other', 'Кола', 'Кола · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('spam', 'fruits', 'Лайм', 'Лайм · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('spam', 'dessert', 'Льодяники', 'Льодяник · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('spam', 'berries', 'Лісові ягоди', 'Малина ожина полуниця чорниця · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Лічі лайм лохина', 'Лічі лайм лохина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Малина', 'Малина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'other', 'Подвійне яблуко', 'Подвійне яблуко аніс · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('spam', 'berries', 'Полуниця кавун', 'Полуниця кавун · Excel category: BERRIES;FRUITS · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Суниця', 'Суниця · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Червоні ягоди', 'Вишня малина полуниця червона смородина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Чорна смородина', 'Чорна смородина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Чорниця', 'Чорниця · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('spam', 'dessert', 'Яблучна цукерка', 'Зелене яблуко цукерка · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('spam', 'dessert', 'Ягідний кекс', 'Кекс ягоди · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('swipe', 'dessert', 'Berry sorbet', 'Морозиво ягоди · Excel category: DESSERTS · Source: Без тютюна', 1, 4, '#c98b3c', true, true, 0),
    ('swipe', 'berries', 'Grape juice', 'Сік чорний виноград · Excel category: BERRIES · Source: Без тютюна', 1, 4, '#c5183a', true, true, 0),
    ('swipe', 'fruits', 'Lemon', 'Лимон · Excel category: FRUITS · Source: Без тютюна', 1, 4, '#f0a523', true, true, 0),
    ('swipe', 'alcohol', 'Margarita', 'Маргарита · Excel category: ALCOHOL · Source: Без тютюна', 1, 4, '#7a2bb8', true, true, 0),
    ('swipe', 'fruits', 'Peach', 'Персик · Excel category: FRUITS · Source: Без тютюна', 1, 4, '#f0a523', true, true, 0),
    ('swipe', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Без тютюна', 1, 4, '#c5183a', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'Blueberry millefeuile', 'Пиріг крем чорниця · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Cheese popcorn', 'Попкорн сир · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'Eskimo', 'Морозиво · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'French vanilla', 'Ваніль · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'Horchata', 'Кориця прянощі вершки · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Ice cactus', 'Кактус лід · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Mushrooms soup', 'Гриби суп · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('turbo-figgy-wan', 'alcohol', 'Pina colada', 'Ананас кокос ром · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('turbo-figgy-wan', 'fruits', 'Pineapple', 'Ананас · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Pizza', 'Піца · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('turbo-figgy-wan', 'berries', 'Raspberry', 'Малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('turbo-figgy-wan', 'fruits', 'Targaryen', 'Гранат · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Well done', 'М''ясо · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'Вівсяне молоко', 'Пластівці молоко · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'dessert', 'Горіхове молоко', 'Горіх молоко · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('turbo-figgy-wan', 'alcohol', 'Капітан блек', 'Ром сигара · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('turbo-figgy-wan', 'other', 'Інжирний лимонад', 'Інжир · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('unity', 'dessert', 'Berry breakfast', 'Вівсянка ягоди · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('unity', 'dessert', 'Berry mochi', 'Полуниця моті чорниця лохина · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('unity', 'other', 'Brazilian tea', 'Лимон чай · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('unity', 'dessert', 'Bubble tea', 'Мармелад молоко чай · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('unity', 'alcohol', 'Champagne papi', 'Шампанське ягоди · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('unity', 'other', 'Corn star', 'Кукурудза · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('unity', 'dessert', 'English tea', 'Бергамот печиво згущене молоко · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('unity', 'dessert', 'Gingy', 'Імбир пиріг · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('unity', 'alcohol', 'Rootman', 'Пиво · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('unity', 'other', 'Salvia', 'Шавлія · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('unity', 'berries', 'Виноградне желе', 'Виноград джем чорний виноград · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('unity', 'alcohol', 'Карибський ром', 'Ром · Excel category: ALCOHOL · Source: Середній', 6, 4, '#7a2bb8', true, true, 0),
    ('unity', 'berries', 'Малина — бузина', 'Малина бузина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('white-side', 'fruits', 'Apricot peach', 'Персик абрикос · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('white-side', 'other', 'Apricot peach Персик абрикос', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('white-side', 'fruits', 'Banana', 'Банан · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('white-side', 'other', 'Green tea', 'Зелений чай · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('white-side', 'other', 'Mystic green', 'Лемонграсс саусеп чорна смородина · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('white-side', 'dessert', 'New frezier', 'Бісквіт полуниця крем · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('white-side', 'other', 'New frezier Бісквіт полуниця крем', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('white-side', 'dessert', 'New lemon pie', 'Лимон пиріг · Excel category: DESSERTS · Source: Середній', 6, 4, '#c98b3c', true, true, 0),
    ('white-side', 'berries', 'New raspberry', 'Малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('white-side', 'other', 'New raspberry малина', 'Excel category: OTHER · Source: Запас', 6, 4, '#8a8f98', true, false, 0),
    ('white-side', 'fruits', 'Pear plum', 'Груша слива · Excel category: FRUITS · Source: Середній', 6, 4, '#f0a523', true, true, 0),
    ('white-side', 'berries', 'Secret', 'Червона смородина малина · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('white-side', 'other', 'Spearmint', 'Жуйка м''ята · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('white-side', 'berries', 'Strawberry', 'Полуниця · Excel category: BERRIES · Source: Середній', 6, 4, '#c5183a', true, true, 0),
    ('white-side', 'other', 'Zen harden', 'Зелений чай лимон м''ята · Excel category: OTHER · Source: Середній', 6, 4, '#8a8f98', true, true, 0),
    ('zodiac', 'fruits', 'Blood orange', 'Апельсин · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('zodiac', 'fruits', 'Citrus sour', 'Апельсин грейпфрут лайм лимон · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('zodiac', 'other', 'Corn star', 'Кукурудза вершки · Excel category: OTHER · Source: Легкий', 3, 4, '#8a8f98', true, true, 0),
    ('zodiac', 'berries', 'Grape splash', 'Виноград сік · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('zodiac', 'fruits', 'Kiwi starfruit', 'Ківі коктейль · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('zodiac', 'fruits', 'Mango passion fruit', 'Манго маракуя · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0),
    ('zodiac', 'dessert', 'Milky way', 'Згущене молоко · Excel category: DESSERTS · Source: Легкий', 3, 4, '#c98b3c', true, true, 0),
    ('zodiac', 'berries', 'Red cherry', 'Вишня · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('zodiac', 'berries', 'Sour berries', 'Бузина журавлина червона смородина · Excel category: BERRIES · Source: Легкий', 3, 4, '#c5183a', true, true, 0),
    ('zodiac', 'fruits', 'Space pear', 'Груша лимонад · Excel category: FRUITS · Source: Легкий', 3, 4, '#f0a523', true, true, 0)
)
INSERT INTO tobaccos (brand_id, category_id, name, description, strength, smoke, color, in_stock, is_active, popularity)
SELECT
  brand.id,
  category.id,
  seed.name,
  seed.description,
  seed.strength,
  seed.smoke,
  seed.color,
  seed.in_stock,
  seed.is_active,
  seed.popularity
FROM tobacco_seed seed
JOIN tobacco_brands brand ON brand.slug = seed.brand_slug
LEFT JOIN flavor_categories category ON category.slug = seed.category_slug
ON CONFLICT (brand_id, name) DO UPDATE
SET category_id = EXCLUDED.category_id,
    description = EXCLUDED.description,
    strength = EXCLUDED.strength,
    smoke = EXCLUDED.smoke,
    color = EXCLUDED.color,
    in_stock = EXCLUDED.in_stock,
    is_active = EXCLUDED.is_active,
    updated_at = now();

COMMIT;
