-- Сховище — актуальний імпорт тютюну
-- Generated from /Users/user/Downloads/tobacco_list.xlsx on 2026-05-29.
-- This reset keeps order history but detaches old preset/order links from catalog entities.
-- Strength in the source sheet is a range; tobaccos.strength is int, so this file stores the upper bound (3/4 -> 4, 5/6 -> 6, 8/10 -> 10).
-- Smoke is 1..5. Exact per-flavor smoke is rarely published; values use researched brand-level notes where available and otherwise default to 4/5.
-- description: customer-facing flavour prose. Strength/smoke live in their own columns, so they are intentionally NOT repeated in the text.
-- image_url: no reliable per-flavour product photos exist for these niche brands. The seed leaves it NULL and the INSERT derives a
--   deterministic placeholder (placehold.co, tinted with the category colour). Replace a row's image_url with a real direct URL to override.

BEGIN;

-- ---------- Reset old catalog data ----------
UPDATE orders SET preset_mix_id = NULL WHERE preset_mix_id IS NOT NULL;
DELETE FROM preset_mix_ingredients;
DELETE FROM preset_mixes;
DELETE FROM tobaccos;
DELETE FROM tobacco_brands;
DELETE FROM flavor_categories;

-- ---------- Flavor categories ----------
INSERT INTO flavor_categories (slug, name, emoji, sort_order) VALUES
  ('berries', 'Ягоди', '🍓', 10),
  ('citrus', 'Цитрус', '🍋', 20),
  ('tropical', 'Тропіки', '🥭', 30),
  ('orchard', 'Садові фрукти', '🍏', 40),
  ('dessert', 'Десерт', '🍰', 50),
  ('candy', 'Цукерки', '🍬', 60),
  ('drinks', 'Напої', '🥤', 70),
  ('mint-cool', 'Холодок', '❄️', 80),
  ('herbal', 'Трави та чай', '🌿', 90),
  ('spicy', 'Пряне', '🌶️', 100),
  ('savory', 'Гастро', '🍕', 110),
  ('tobacco', 'Тютюнові', '🚬', 120),
  ('other', 'Інше', '✨', 900);

-- ---------- Brands ----------
INSERT INTO tobacco_brands (slug, name, is_active) VALUES
  ('spam', 'Spam', true),
  ('mint', 'Mint', true),
  ('swipe', 'Swipe', true),
  ('orwel-soft', 'Orwel soft', true),
  ('buta', 'Buta', true),
  ('zodiac', 'Zodiac', true),
  ('starz', 'Starz', true),
  ('space-tea', 'Space tea', true),
  ('arawak', 'Arawak', true),
  ('gastro-line', 'Gastro line', true),
  ('chefs', 'Chef''s', true),
  ('lagom', 'Lagom', true),
  ('420', '420', true),
  ('buta-black', 'Buta black', true),
  ('dead-horse', 'Dead horse', true),
  ('unity', 'Unity', true),
  ('custom', 'Custom', true),
  ('orwel', 'Orwel', true),
  ('creepy', 'Creepy', true),
  ('enigma', 'Enigma', true),
  ('orwel-strong', 'Orwel strong', true),
  ('heaven', 'Heaven', true);

-- ---------- Tobaccos ----------
WITH tobacco_seed (brand_slug, category_slug, name, description, strength, smoke, image_url, color, in_stock, is_active, popularity) AS (
  VALUES
    ('spam', 'other', 'Spam', 'Фірмова суміш бренду — збалансований профіль без різкої домінанти.', 4, 4, NULL, '#8a8f98', true, true, 0),
    ('spam', 'dessert', 'Ягідний кекс', 'Здобний кекс із теплим ягідним прошарком.', 4, 4, NULL, '#c98b3c', true, true, 0),
    ('spam', 'citrus', 'Анельсин мандарин', 'Соковитий апельсин із цедрою мандарина.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'berries', 'Лісові Ягоди', 'Кошик лісових ягід — суниця, чорниця й ожина разом.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'drinks', 'Кола', 'Класична кола з бульбашками й карамельним хвостиком.', 4, 4, NULL, '#7a2bb8', true, true, 0),
    ('spam', 'tropical', 'Кокос ананас диня', 'Тропічне тріо — вершковий кокос, ананас і медова диня.', 4, 4, NULL, '#f0a523', true, true, 0),
    ('spam', 'candy', 'Яблучна цукерка', 'Льодяникове зелене яблуко — солодке з кислинкою.', 4, 4, NULL, '#ff4d8d', true, true, 0),
    ('spam', 'berries', 'Суниця', 'Лугова суниця — ніжна й духмяна.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Вишня', 'Спіла вишня з легкою кісточковою гірчинкою.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'citrus', 'Ананас лимон', 'Кислий ананас із лимонним фрешем.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'orchard', 'Подвійне яблуко', 'Класичне подвійне яблуко з анісовою ноткою.', 4, 4, NULL, '#a8b53a', true, true, 0),
    ('spam', 'citrus', 'Лайм персик', 'Соковитий персик, освіжений лаймом.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'candy', 'Льодяники', 'Барбарисові льодяники з дитинства.', 4, 4, NULL, '#ff4d8d', true, true, 0),
    ('spam', 'tropical', 'Екзотичні фрукти', 'Мікс екзотики — манго, маракуя й папая.', 4, 4, NULL, '#f0a523', true, true, 0),
    ('spam', 'orchard', 'Кавун диня', 'Соковитий кавун і медова диня — смак літа.', 4, 4, NULL, '#a8b53a', true, true, 0),
    ('spam', 'candy', 'Желейні ведмедики', 'Фруктові желейні ведмедики — солодка ностальгія.', 4, 4, NULL, '#ff4d8d', true, true, 0),
    ('spam', 'berries', 'Чорна смородина', 'Густа чорна смородина з листяною свіжістю.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'citrus', 'Лайм', 'Чистий зелений лайм — різкий і свіжий.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'berries', 'Полуниця кавун', 'Стигла полуниця із соковитим кавуном.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'orchard', 'Абрикос', 'Стиглий абрикос — м’який і медовий.', 4, 4, NULL, '#a8b53a', true, true, 0),
    ('spam', 'citrus', 'Бергамот ківі', 'Чайний бергамот із кислинкою ківі.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'citrus', 'Грейпфрут', 'Рожевий грейпфрут із характерною гірчинкою.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'citrus', 'Лимон', 'Сонячний лимон — яскравий і кислий.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('spam', 'other', 'Зелений мікс', 'Свіжий мікс зелених фруктів із прохолодою.', 4, 4, NULL, '#8a8f98', true, true, 0),
    ('spam', 'berries', 'Виноград ягоди', 'Солодкий виноград у компанії лісових ягід.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'drinks', 'Кавуновий лимонад', 'Освіжний кавуновий лимонад із льодом.', 4, 4, NULL, '#7a2bb8', true, true, 0),
    ('spam', 'drinks', 'Енергетик', 'Цитрусовий енергетик — бадьорий і солодкий.', 4, 4, NULL, '#7a2bb8', true, true, 0),
    ('spam', 'berries', 'Вишня папая', 'Спіла вишня, пом’якшена тропічною папаєю.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Червоні ягоди', 'Букет червоних ягід — полуниця, малина, вишня.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'mint-cool', 'Екліпс', 'Глибокий холодок без зайвого смаку — чиста прохолода.', 4, 4, NULL, '#1ec27a', true, true, 0),
    ('spam', 'berries', 'Лічі лайм лохина', 'Екзотичне лічі, лайм і прохолодна лохина.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('spam', 'berries', 'Чорниця', 'Лісова чорниця — солодка з легкою терпкістю.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('mint', 'orchard', 'Груша яблуко', 'Соковита груша й хрустке яблуко.', 4, 4, NULL, '#a8b53a', true, true, 0),
    ('mint', 'tropical', 'Ананас манго маракуя', 'Тропічний коктейль — ананас, манго й маракуя.', 4, 4, NULL, '#f0a523', true, true, 0),
    ('mint', 'citrus', 'Лимон', 'Свіжий лимонний фреш.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('mint', 'berries', 'Лічі малина', 'Солодке лічі з кислинкою малини.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('mint', 'mint-cool', 'Айс персик', 'Стиглий персик із крижаним холодком.', 4, 4, NULL, '#1ec27a', true, true, 0),
    ('swipe', 'drinks', 'Маргарита', 'Коктейль маргарита — лайм і сіль. Без нікотину.', 1, 4, NULL, '#7a2bb8', true, true, 0),
    ('swipe', 'berries', 'Ягідний сорбет', 'Прохолодний ягідний сорбет. Без нікотину.', 1, 4, NULL, '#c5183a', true, true, 0),
    ('swipe', 'berries', 'Виноградний сік', 'Солодкий виноградний сік. Без нікотину.', 1, 4, NULL, '#c5183a', true, true, 0),
    ('swipe', 'citrus', 'Лимон', 'Освіжний лимон. Без нікотину.', 1, 4, NULL, '#ff8a3d', true, true, 0),
    ('swipe', 'berries', 'Малина', 'Спіла садова малина. Без нікотину.', 1, 4, NULL, '#c5183a', true, true, 0),
    ('orwel-soft', 'candy', 'Чорнична жуйка', 'Чорнична жувальна гумка — солодко й грайливо.', 4, 4, NULL, '#ff4d8d', true, true, 0),
    ('orwel-soft', 'berries', 'Чорниця з льодом', 'Лісова чорниця, охолоджена льодом.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('orwel-soft', 'berries', 'Полуничне фраголіно', 'Полуничне ігристе фраголіно.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('orwel-soft', 'dessert', 'Сливовий джем', 'Густий домашній сливовий джем.', 4, 4, NULL, '#c98b3c', true, true, 0),
    ('orwel-soft', 'berries', 'Малина', 'Соковита садова малина.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('orwel-soft', 'tropical', 'Ананас', 'Соковитий тропічний ананас.', 4, 4, NULL, '#f0a523', true, true, 0),
    ('orwel-soft', 'citrus', 'Грейпфрут', 'Рожевий грейпфрут із приємною гірчинкою.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('orwel-soft', 'citrus', 'Цитрус з льодом', 'Цитрусовий мікс із крижаною свіжістю.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('buta', 'berries', 'Полуниця', 'Ароматна стигла полуниця.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('buta', 'berries', 'Малина', 'Соковита малина просто з куща.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('zodiac', 'berries', 'Виноградний сік', 'Густий солодкий виноградний сік.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('zodiac', 'tropical', 'Кисле ківі', 'Кисле зелене ківі — яскраво й тонізує.', 4, 4, NULL, '#f0a523', true, true, 0),
    ('zodiac', 'dessert', 'Згущене молоко', 'Карамельне згущене молоко — вершково й солодко.', 4, 4, NULL, '#c98b3c', true, true, 0),
    ('starz', 'citrus', 'Апельсин', 'Соковитий солодкий апельсин.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('starz', 'citrus', 'Кислий цитрус', 'Мікс кислих цитрусів — бадьорить.', 4, 4, NULL, '#ff8a3d', true, true, 0),
    ('starz', 'berries', 'Вишня', 'Спіла темна вишня.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('starz', 'berries', 'Кислі ягоди', 'Букет кислих ягід — освіжає.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('space-tea', 'citrus', 'Сицилійський апельсин', 'Яскравий сицилійський апельсин у густій хмарі.', 4, 5, NULL, '#ff8a3d', true, true, 0),
    ('space-tea', 'berries', 'Чорниця', 'Лісова чорниця з насиченим димом.', 4, 5, NULL, '#c5183a', true, true, 0),
    ('space-tea', 'berries', 'Ягідний шторм', 'Буря лісових ягід — потужна хмара.', 4, 5, NULL, '#c5183a', true, true, 0),
    ('arawak', 'other', 'Кисла фанта', 'Газована кисла фанта — апельсинова шипучка.', 4, 4, NULL, '#8a8f98', true, true, 0),
    ('arawak', 'candy', 'Кавунова жуйка', 'Кавунова жувальна гумка.', 4, 4, NULL, '#ff4d8d', true, true, 0),
    ('arawak', 'berries', 'Малина', 'Соковита садова малина.', 4, 4, NULL, '#c5183a', true, true, 0),
    ('gastro-line', 'savory', 'Грибний суп', 'Наваристий грибний крем-суп — несподівано смачно.', 6, 4, NULL, '#bd6932', true, true, 0),
    ('gastro-line', 'savory', 'Піца', 'Запечена піца з томатом і розплавленим сиром.', 6, 4, NULL, '#bd6932', true, true, 0),
    ('gastro-line', 'savory', 'Бужаніна', 'Печена бужаніна з димком — для сміливих.', 6, 4, NULL, '#bd6932', true, true, 0),
    ('chefs', 'berries', 'Lil grape', 'Дрібний солодкий виноград.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('chefs', 'berries', 'Sour cherry', 'Кисла вишня з яскравим хвостиком.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('chefs', 'citrus', 'Sour lemon', 'Різкий кислий лимон.', 6, 4, NULL, '#ff8a3d', true, true, 0),
    ('chefs', 'tropical', 'Pepsi mango', 'Кола із соковитим манго.', 6, 4, NULL, '#f0a523', true, true, 0),
    ('chefs', 'dessert', 'Cream likor', 'Вершковий лікер — м’який десерт.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('chefs', 'tropical', 'Sour pineapple', 'Кислий соковитий ананас.', 6, 4, NULL, '#f0a523', true, true, 0),
    ('chefs', 'orchard', 'Sweet watermelon', 'Солодкий стиглий кавун.', 6, 4, NULL, '#a8b53a', true, true, 0),
    ('chefs', 'berries', 'Sour blueberries', 'Кисла лісова чорниця.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('lagom', 'other', 'Lavadeful', 'Авторська лавандова суміш — квітково й м’яко.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('lagom', 'other', 'Fjord', 'Свіжий скандинавський мікс із прохолодою.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('lagom', 'other', 'Glogg', 'Пряний глінтвейн — спеції й тепле вино.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('lagom', 'other', 'Crazy frog', 'Грайливий фруктово-цукерковий мікс.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('lagom', 'herbal', 'Fireflower', 'Трав’яний настій із вогняною пряністю.', 6, 4, NULL, '#5d8f4a', true, true, 0),
    ('420', 'citrus', 'Кактус лимон лайм ківі', 'Кактус, лимон, лайм і ківі — свіжий заряд.', 6, 5, NULL, '#ff8a3d', true, true, 0),
    ('420', 'orchard', 'Кавун текіла лайв', 'Соковитий кавун із текілою — коктейльна вечірка.', 6, 5, NULL, '#a8b53a', true, true, 0),
    ('420', 'citrus', 'Маракуя лимон ігристе', 'Маракуя й лимон в ігристому вині.', 6, 5, NULL, '#ff8a3d', true, true, 0),
    ('420', 'orchard', 'Гарбузове каша', 'Гарбузова каша з медом — затишний десерт.', 6, 5, NULL, '#a8b53a', true, true, 0),
    ('420', 'candy', 'Барбарисова цукерка', 'Класичний барбарисовий льодяник.', 6, 5, NULL, '#ff4d8d', true, true, 0),
    ('420', 'other', 'Памело', 'Соковите памело з легкою гірчинкою.', 6, 5, NULL, '#8a8f98', true, true, 0),
    ('buta-black', 'drinks', 'Horchata', 'Орчата — рисовий напій із корицею.', 6, 5, NULL, '#7a2bb8', true, true, 0),
    ('buta-black', 'other', 'Eskimo', 'Вершкове ескімо — пломбір у шоколаді.', 6, 5, NULL, '#8a8f98', true, true, 0),
    ('dead-horse', 'drinks', 'Ліптон', 'Холодний чай ліптон із лимоном.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('dead-horse', 'drinks', 'Апельсиновий лікер', 'Апельсиновий лікер — цитрус і солодкий спирт.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('dead-horse', 'berries', 'Манго полуниця кокос', 'Манго, полуниця й вершковий кокос.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('dead-horse', 'berries', 'Виноградний сік', 'Густий солодкий виноградний сік.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('dead-horse', 'dessert', 'Крем сода лимон памело', 'Крем-сода з лимоном і памело.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('dead-horse', 'dessert', 'Пончик бой', 'Свіжий пончик із цукровою глазур’ю.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('dead-horse', 'drinks', 'Червоне вино', 'Сухе червоне вино — глибокий виноград.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('unity', 'drinks', 'Рутбир', 'Американський рутбір — пряні трави й карамель.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('unity', 'savory', 'Кукуруза', 'Солодка варена кукурудза.', 6, 4, NULL, '#bd6932', true, true, 0),
    ('unity', 'spicy', 'Імбірний пряник', 'Імбірний пряник зі святковими спеціями.', 6, 4, NULL, '#ff4500', true, true, 0),
    ('unity', 'drinks', 'Бразильський чай', 'Тонізуючий бразильський мате.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('unity', 'berries', 'Виноградне желе', 'Желе зі стиглого винограду.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('unity', 'dessert', 'Ягідний сніданок', 'Ягоди з вершками й гранолою.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('unity', 'dessert', 'Ягідний моті', 'Японський моті з ягідною начинкою.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('unity', 'drinks', 'Карибський ром', 'Витриманий карибський ром.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('custom', 'citrus', 'Зелений лайм', 'Свіжий зелений лайм.', 6, 4, NULL, '#ff8a3d', true, true, 0),
    ('custom', 'candy', 'Вишня цукерка', 'Вишневий льодяник.', 6, 4, NULL, '#ff4d8d', true, true, 0),
    ('custom', 'berries', 'Лічі полуниця', 'Екзотичне лічі зі стиглою полуницею.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('custom', 'candy', 'Барбарис цукерка', 'Барбарисова цукерка з дитинства.', 6, 4, NULL, '#ff4d8d', true, true, 0),
    ('custom', 'berries', 'Кислюча малина', 'Дуже кисла малина — яскравий удар.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('custom', 'dessert', 'Груша джем', 'Густий грушевий джем.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('custom', 'citrus', 'Памело лимон', 'Памело з лимонною свіжістю.', 6, 4, NULL, '#ff8a3d', true, true, 0),
    ('custom', 'dessert', 'Кавун морозиво', 'Кавунове морозиво — солодко й прохолодно.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('custom', 'other', 'Рожевий бабл гам', 'Рожева жувальна гумка — солодка ностальгія.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('custom', 'dessert', 'Мед', 'Густий квітковий мед.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('custom', 'berries', 'Йошта агрус', 'Йошта й агрус — кисло-солодкі садові ягоди.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('custom', 'orchard', 'Сидр яблуко', 'Яблучний сидр — ігристий і терпкий.', 6, 4, NULL, '#a8b53a', true, true, 0),
    ('custom', 'other', 'Логан фрукт', 'Екзотичний логан — солодкий і соковитий.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('orwel', 'citrus', 'Лимон', 'Яскравий кислий лимон.', 6, 4, NULL, '#ff8a3d', true, true, 0),
    ('orwel', 'tropical', 'Ананас', 'Соковитий тропічний ананас.', 6, 4, NULL, '#f0a523', true, true, 0),
    ('orwel', 'drinks', 'Персиковий чай', 'Холодний чай зі стиглим персиком.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('orwel', 'candy', 'Темний льодяник', 'Темний барбарисовий льодяник.', 6, 4, NULL, '#ff4d8d', true, true, 0),
    ('orwel', 'berries', 'Чорниця з льодом', 'Лісова чорниця з крижаним холодком.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'berries', 'Ягідно-хвойний коктейль', 'Лісові ягоди з хвойною свіжістю.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'tropical', 'Манго-маракуя', 'Соковите манго з кислою маракуєю.', 6, 4, NULL, '#f0a523', true, true, 0),
    ('orwel', 'drinks', 'Сік лайму', 'Свіжовичавлений сік лайму.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('orwel', 'candy', 'Чорнична жуйка', 'Чорнична жувальна гумка.', 6, 4, NULL, '#ff4d8d', true, true, 0),
    ('orwel', 'candy', 'Желейні червʼячки', 'Кисло-солодкі желейні черв’ячки.', 6, 4, NULL, '#ff4d8d', true, true, 0),
    ('orwel', 'citrus', 'Грейпфрут', 'Рожевий грейпфрут із гірчинкою.', 6, 4, NULL, '#ff8a3d', true, true, 0),
    ('orwel', 'berries', 'Вишня-гранат', 'Спіла вишня з терпким гранатом.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'berries', 'Полуничне фраголіно', 'Полуничне ігристе фраголіно.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'dessert', 'Сливовий джем', 'Густий домашній сливовий джем.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('orwel', 'berries', 'Мікс ягід', 'Букет садових ягід.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'tropical', 'Фейхоа-ківі', 'Ароматна фейхоа з кислим ківі.', 6, 4, NULL, '#f0a523', true, true, 0),
    ('orwel', 'drinks', 'Цитрусовий енергетик', 'Цитрусовий енергетик — бадьорий заряд.', 6, 4, NULL, '#7a2bb8', true, true, 0),
    ('orwel', 'mint-cool', 'Мʼята', 'Чиста прохолодна м’ята.', 6, 4, NULL, '#1ec27a', true, true, 0),
    ('orwel', 'berries', 'Ягідний десерт', 'Ягоди з вершковим кремом.', 6, 4, NULL, '#c5183a', true, true, 0),
    ('orwel', 'other', 'Мультифрукт (capri sun)', 'Дитячий мультифруктовий сік.', 6, 4, NULL, '#8a8f98', true, true, 0),
    ('orwel', 'dessert', 'Ванільна кола', 'Кола з ванільним відтінком.', 6, 4, NULL, '#c98b3c', true, true, 0),
    ('creepy', 'other', 'Krampus', 'Темна пряна суміш — міцний характер.', 10, 4, NULL, '#8a8f98', true, true, 0),
    ('creepy', 'berries', 'Strawberry dessert', 'Полуничний десерт із вершками.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('creepy', 'tropical', 'Banana', 'Стиглий вершковий банан.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('enigma', 'other', 'Pyrastep', 'Авторська загадкова суміш — насичений профіль.', 10, 4, NULL, '#8a8f98', true, true, 0),
    ('enigma', 'other', 'Granadilla', 'Гранадилла — солодка родичка маракуї.', 10, 4, NULL, '#8a8f98', true, true, 0),
    ('enigma', 'spicy', 'Kashmir', 'Кашмірські спеції — тепло й пряно.', 10, 4, NULL, '#ff4500', true, true, 0),
    ('enigma', 'other', 'Fragaria', 'Лісова суниця — концентрований аромат.', 10, 4, NULL, '#8a8f98', true, true, 0),
    ('enigma', 'other', 'Anablanka', 'Ананас із вершковим відтінком.', 10, 4, NULL, '#8a8f98', true, true, 0),
    ('enigma', 'mint-cool', 'Arctic', 'Арктичний холод — крижана прохолода.', 10, 4, NULL, '#1ec27a', true, true, 0),
    ('orwel-strong', 'citrus', 'Цитрус з льодом', 'Цитрусовий мікс із крижаною свіжістю.', 10, 4, NULL, '#ff8a3d', true, true, 0),
    ('orwel-strong', 'berries', 'Мікс ягід', 'Букет садових ягід.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('orwel-strong', 'mint-cool', 'Леді кілер', 'Потужний холодок із ягідним хвостиком.', 10, 4, NULL, '#1ec27a', true, true, 0),
    ('orwel-strong', 'drinks', 'Цитрусовий енергетик', 'Цитрусовий енергетик — міцний заряд.', 10, 4, NULL, '#7a2bb8', true, true, 0),
    ('heaven', 'orchard', 'Стигла диня', 'Медова стигла диня.', 10, 4, NULL, '#a8b53a', true, true, 0),
    ('heaven', 'drinks', 'Апельсиновий сік', 'Свіжий апельсиновий фреш.', 10, 4, NULL, '#7a2bb8', true, true, 0),
    ('heaven', 'tropical', 'Гранатовий фреш', 'Терпкий гранатовий сік.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'candy', 'Желейна кола', 'Желейна кола — цукрова жуйка.', 10, 4, NULL, '#ff4d8d', true, true, 0),
    ('heaven', 'berries', 'Малина', 'Соковита садова малина.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'orchard', 'Зимова груша', 'Соковита зимова груша.', 10, 4, NULL, '#a8b53a', true, true, 0),
    ('heaven', 'citrus', 'Кислий цитрус', 'Мікс кислих цитрусів.', 10, 4, NULL, '#ff8a3d', true, true, 0),
    ('heaven', 'berries', 'Мікс ягід', 'Букет садових ягід.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'berries', 'Подвійне яблуко персик полуниця', 'Подвійне яблуко з персиком і полуницею.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'berries', 'Темна вишня', 'Спіла темна вишня.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'drinks', 'Енергетик', 'Цитрусовий енергетик — потужний заряд.', 10, 4, NULL, '#7a2bb8', true, true, 0),
    ('heaven', 'tropical', 'Ківі', 'Кисле зелене ківі.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'tropical', 'Тропічний мікс', 'Коктейль тропічних фруктів.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'berries', 'Полуниця суниця', 'Полуниця з лісовою суницею.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'citrus', 'Лимон', 'Яскравий кислий лимон.', 10, 4, NULL, '#ff8a3d', true, true, 0),
    ('heaven', 'orchard', 'Нектарин абрикос', 'Стиглі нектарин і абрикос.', 10, 4, NULL, '#a8b53a', true, true, 0),
    ('heaven', 'citrus', 'Грейпфрут', 'Рожевий грейпфрут із гірчинкою.', 10, 4, NULL, '#ff8a3d', true, true, 0),
    ('heaven', 'drinks', 'Шот еспресо', 'Міцний шот еспресо.', 10, 4, NULL, '#7a2bb8', true, true, 0),
    ('heaven', 'berries', 'Чорна смородина', 'Густа чорна смородина.', 10, 4, NULL, '#c5183a', true, true, 0),
    ('heaven', 'tropical', 'Кислий ананас', 'Кислий соковитий ананас.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'tropical', 'Маракуя', 'Кисло-солодка тропічна маракуя.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'dessert', 'Полуничний кекс', 'Здобний кекс із полуницею.', 10, 4, NULL, '#c98b3c', true, true, 0),
    ('heaven', 'dessert', 'Баунті', 'Кокос у молочному шоколаді.', 10, 4, NULL, '#c98b3c', true, true, 0),
    ('heaven', 'drinks', 'Дайкірі', 'Коктейль дайкірі — ром і лайм.', 10, 4, NULL, '#7a2bb8', true, true, 0),
    ('heaven', 'tropical', 'Манго', 'Соковите тропічне манго.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'tropical', 'Банан', 'Стиглий вершковий банан.', 10, 4, NULL, '#f0a523', true, true, 0),
    ('heaven', 'herbal', 'Хвоя', 'Свіжа хвоя — смолистий ліс.', 10, 4, NULL, '#5d8f4a', true, true, 0),
    ('heaven', 'orchard', 'Кавун', 'Соковитий стиглий кавун.', 10, 4, NULL, '#a8b53a', true, true, 0),
    ('heaven', 'berries', 'Малина чорниця', 'Малина з лісовою чорницею.', 10, 4, NULL, '#c5183a', true, true, 0)
)
INSERT INTO tobaccos (brand_id, category_id, name, description, strength, smoke, image_url, color, in_stock, is_active, popularity)
SELECT
  brand.id,
  category.id,
  seed.name,
  seed.description,
  seed.strength,
  seed.smoke,
  seed.image_url,
  seed.color,
  seed.in_stock,
  seed.is_active,
  seed.popularity
FROM tobacco_seed seed
JOIN tobacco_brands brand ON brand.slug = seed.brand_slug
JOIN flavor_categories category ON category.slug = seed.category_slug;

COMMIT;

-- Dropped duplicate source rows:
--   row 34: Spam · Абрикос
